# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'QueryTable4.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_QueryTable4(object):
    def setupUi(self, QueryTable4):
        QueryTable4.setObjectName("QueryTable4")
        QueryTable4.resize(1326, 827)
        QueryTable4.setStyleSheet("background-color:rgb(174, 221, 242)")
        self.textEdit_13 = QtWidgets.QTextEdit(QueryTable4)
        self.textEdit_13.setGeometry(QtCore.QRect(510, 380, 151, 31))
        self.textEdit_13.setStyleSheet("background-color:rgb(255, 255, 255);\n"
"border:2px solid;\n"
"border-radius:10;\n"
"")
        self.textEdit_13.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.textEdit_13.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textEdit_13.setObjectName("textEdit_13")
        self.spinBox_7 = QtWidgets.QSpinBox(QueryTable4)
        self.spinBox_7.setGeometry(QtCore.QRect(370, 380, 131, 31))
        self.spinBox_7.setStyleSheet("background-color:rgb(255, 255, 255);\n"
"border:2px solid;\n"
"border-radius:10;\n"
"")
        self.spinBox_7.setAlignment(QtCore.Qt.AlignCenter)
        self.spinBox_7.setObjectName("spinBox_7")
        self.label_8 = QtWidgets.QLabel(QueryTable4)
        self.label_8.setGeometry(QtCore.QRect(680, 20, 241, 31))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_8.setStyleSheet("background-color: rgb(250, 250, 125);\n"
"border:2px solid;\n"
"border-radius:10;\n"
"")
        self.label_8.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.textEdit_19 = QtWidgets.QTextEdit(QueryTable4)
        self.textEdit_19.setGeometry(QtCore.QRect(20, 420, 341, 31))
        self.textEdit_19.setStyleSheet("background-color:rgb(255, 255, 255);\n"
"border:2px solid;\n"
"border-radius:10;\n"
"")
        self.textEdit_19.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textEdit_19.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textEdit_19.setObjectName("textEdit_19")
        self.textEdit_54 = QtWidgets.QTextEdit(QueryTable4)
        self.textEdit_54.setGeometry(QtCore.QRect(680, 340, 341, 31))
        self.textEdit_54.setStyleSheet("background-color:rgb(255, 255, 255);\n"
"border:2px solid;\n"
"border-radius:10;\n"
"")
        self.textEdit_54.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textEdit_54.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textEdit_54.setObjectName("textEdit_54")
        self.textEdit_44 = QtWidgets.QTextEdit(QueryTable4)
        self.textEdit_44.setGeometry(QtCore.QRect(680, 420, 341, 31))
        self.textEdit_44.setStyleSheet("background-color:rgb(255, 255, 255);\n"
"border:2px solid;\n"
"border-radius:10;\n"
"")
        self.textEdit_44.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textEdit_44.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textEdit_44.setObjectName("textEdit_44")
        self.textEdit_3 = QtWidgets.QTextEdit(QueryTable4)
        self.textEdit_3.setGeometry(QtCore.QRect(20, 140, 341, 31))
        self.textEdit_3.setStyleSheet("background-color:rgb(255, 255, 255);\n"
"border:2px solid;\n"
"border-radius:10;\n"
"")
        self.textEdit_3.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textEdit_3.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textEdit_3.setObjectName("textEdit_3")
        self.textEdit_20 = QtWidgets.QTextEdit(QueryTable4)
        self.textEdit_20.setGeometry(QtCore.QRect(20, 380, 341, 31))
        self.textEdit_20.setStyleSheet("background-color:rgb(255, 255, 255);\n"
"border:2px solid;\n"
"border-radius:10;\n"
"")
        self.textEdit_20.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textEdit_20.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textEdit_20.setObjectName("textEdit_20")
        self.textEdit_42 = QtWidgets.QTextEdit(QueryTable4)
        self.textEdit_42.setGeometry(QtCore.QRect(1170, 220, 151, 31))
        self.textEdit_42.setStyleSheet("background-color:rgb(255, 255, 255);\n"
"border:2px solid;\n"
"border-radius:10;\n"
"")
        self.textEdit_42.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.textEdit_42.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textEdit_42.setObjectName("textEdit_42")
        self.spinBox_17 = QtWidgets.QSpinBox(QueryTable4)
        self.spinBox_17.setGeometry(QtCore.QRect(1030, 420, 131, 31))
        self.spinBox_17.setStyleSheet("background-color:rgb(255, 255, 255);\n"
"border:2px solid;\n"
"border-radius:10;\n"
"")
        self.spinBox_17.setAlignment(QtCore.Qt.AlignCenter)
        self.spinBox_17.setObjectName("spinBox_17")
        self.spinBox = QtWidgets.QSpinBox(QueryTable4)
        self.spinBox.setGeometry(QtCore.QRect(370, 100, 131, 31))
        self.spinBox.setStyleSheet("background-color:rgb(255, 255, 255);\n"
"border:2px solid;\n"
"border-radius:10;\n"
"")
        self.spinBox.setAlignment(QtCore.Qt.AlignCenter)
        self.spinBox.setObjectName("spinBox")
        self.textEdit_31 = QtWidgets.QTextEdit(QueryTable4)
        self.textEdit_31.setGeometry(QtCore.QRect(270, 540, 391, 31))
        self.textEdit_31.setStyleSheet("background-color:rgb(255, 255, 255);\n"
"border:2px solid;\n"
"border-radius:10;\n"
"")
        self.textEdit_31.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.textEdit_31.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textEdit_31.setObjectName("textEdit_31")
        self.textEdit_26 = QtWidgets.QTextEdit(QueryTable4)
        self.textEdit_26.setGeometry(QtCore.QRect(510, 740, 151, 31))
        self.textEdit_26.setStyleSheet("background-color:rgb(255, 255, 255);\n"
"border:2px solid;\n"
"border-radius:10;\n"
"")
        self.textEdit_26.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.textEdit_26.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textEdit_26.setObjectName("textEdit_26")
        self.textEdit_23 = QtWidgets.QTextEdit(QueryTable4)
        self.textEdit_23.setGeometry(QtCore.QRect(20, 580, 341, 31))
        self.textEdit_23.setStyleSheet("background-color:rgb(255, 255, 255);\n"
"border:2px solid;\n"
"border-radius:10;\n"
"")
        self.textEdit_23.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textEdit_23.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textEdit_23.setObjectName("textEdit_23")
        self.spinBox_3 = QtWidgets.QSpinBox(QueryTable4)
        self.spinBox_3.setGeometry(QtCore.QRect(370, 180, 131, 31))
        self.spinBox_3.setStyleSheet("background-color:rgb(255, 255, 255);\n"
"border:2px solid;\n"
"border-radius:10;\n"
"")
        self.spinBox_3.setAlignment(QtCore.Qt.AlignCenter)
        self.spinBox_3.setObjectName("spinBox_3")
        self.spinBox_22 = QtWidgets.QSpinBox(QueryTable4)
        self.spinBox_22.setGeometry(QtCore.QRect(1030, 300, 131, 31))
        self.spinBox_22.setStyleSheet("background-color:rgb(255, 255, 255);\n"
"border:2px solid;\n"
"border-radius:10;\n"
"")
        self.spinBox_22.setAlignment(QtCore.Qt.AlignCenter)
        self.spinBox_22.setObjectName("spinBox_22")
        self.textEdit_34 = QtWidgets.QTextEdit(QueryTable4)
        self.textEdit_34.setGeometry(QtCore.QRect(1170, 60, 151, 31))
        self.textEdit_34.setStyleSheet("background-color:rgb(255, 255, 255);\n"
"border:2px solid;\n"
"border-radius:10;\n"
"")
        self.textEdit_34.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.textEdit_34.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textEdit_34.setObjectName("textEdit_34")
        self.textEdit_37 = QtWidgets.QTextEdit(QueryTable4)
        self.textEdit_37.setGeometry(QtCore.QRect(1170, 380, 151, 31))
        self.textEdit_37.setStyleSheet("background-color:rgb(255, 255, 255);\n"
"border:2px solid;\n"
"border-radius:10;\n"
"")
        self.textEdit_37.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.textEdit_37.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textEdit_37.setObjectName("textEdit_37")
        self.textEdit_2 = QtWidgets.QTextEdit(QueryTable4)
        self.textEdit_2.setGeometry(QtCore.QRect(20, 100, 341, 31))
        self.textEdit_2.setStyleSheet("background-color:rgb(255, 255, 255);\n"
"border:2px solid;\n"
"border-radius:10;\n"
"")
        self.textEdit_2.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textEdit_2.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textEdit_2.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.textEdit_2.setObjectName("textEdit_2")
        self.textEdit_47 = QtWidgets.QTextEdit(QueryTable4)
        self.textEdit_47.setGeometry(QtCore.QRect(930, 20, 391, 31))
        self.textEdit_47.setStyleSheet("background-color:rgb(255, 255, 255);\n"
"border:2px solid;\n"
"border-radius:10;\n"
"")
        self.textEdit_47.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.textEdit_47.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textEdit_47.setObjectName("textEdit_47")
        self.textEdit_43 = QtWidgets.QTextEdit(QueryTable4)
        self.textEdit_43.setGeometry(QtCore.QRect(680, 220, 341, 31))
        self.textEdit_43.setStyleSheet("background-color:rgb(255, 255, 255);\n"
"border:2px solid;\n"
"border-radius:10;\n"
"")
        self.textEdit_43.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textEdit_43.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textEdit_43.setObjectName("textEdit_43")
        self.textEdit_24 = QtWidgets.QTextEdit(QueryTable4)
        self.textEdit_24.setGeometry(QtCore.QRect(20, 700, 341, 31))
        self.textEdit_24.setStyleSheet("background-color:rgb(255, 255, 255);\n"
"border:2px solid;\n"
"border-radius:10;\n"
"")
        self.textEdit_24.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textEdit_24.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textEdit_24.setObjectName("textEdit_24")
        self.textEdit = QtWidgets.QTextEdit(QueryTable4)
        self.textEdit.setGeometry(QtCore.QRect(270, 20, 391, 31))
        self.textEdit.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.textEdit.setStyleSheet("background-color:rgb(255, 255, 255);\n"
"border:2px solid;\n"
"border-radius:10;\n"
"")
        self.textEdit.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.textEdit.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textEdit.setObjectName("textEdit")
        self.textEdit_38 = QtWidgets.QTextEdit(QueryTable4)
        self.textEdit_38.setGeometry(QtCore.QRect(1170, 180, 151, 31))
        self.textEdit_38.setStyleSheet("background-color:rgb(255, 255, 255);\n"
"border:2px solid;\n"
"border-radius:10;\n"
"")
        self.textEdit_38.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.textEdit_38.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textEdit_38.setObjectName("textEdit_38")
        self.label = QtWidgets.QLabel(QueryTable4)
        self.label.setGeometry(QtCore.QRect(20, 20, 241, 31))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label.setStyleSheet("background-color: rgb(250, 250, 125);\n"
"border:2px solid;\n"
"border-radius:10;\n"
"")
        self.label.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.textEdit_50 = QtWidgets.QTextEdit(QueryTable4)
        self.textEdit_50.setGeometry(QtCore.QRect(680, 300, 341, 31))
        self.textEdit_50.setStyleSheet("background-color:rgb(255, 255, 255);\n"
"border:2px solid;\n"
"border-radius:10;\n"
"")
        self.textEdit_50.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textEdit_50.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textEdit_50.setObjectName("textEdit_50")
        self.spinBox_9 = QtWidgets.QSpinBox(QueryTable4)
        self.spinBox_9.setGeometry(QtCore.QRect(370, 420, 131, 31))
        self.spinBox_9.setStyleSheet("background-color:rgb(255, 255, 255);\n"
"border:2px solid;\n"
"border-radius:10;\n"
"")
        self.spinBox_9.setAlignment(QtCore.Qt.AlignCenter)
        self.spinBox_9.setObjectName("spinBox_9")
        self.textEdit_53 = QtWidgets.QTextEdit(QueryTable4)
        self.textEdit_53.setGeometry(QtCore.QRect(680, 180, 341, 31))
        self.textEdit_53.setStyleSheet("background-color:rgb(255, 255, 255);\n"
"border:2px solid;\n"
"border-radius:10;\n"
"")
        self.textEdit_53.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textEdit_53.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textEdit_53.setObjectName("textEdit_53")
        self.spinBox_10 = QtWidgets.QSpinBox(QueryTable4)
        self.spinBox_10.setGeometry(QtCore.QRect(370, 340, 131, 31))
        self.spinBox_10.setStyleSheet("background-color:rgb(255, 255, 255);\n"
"border:2px solid;\n"
"border-radius:10;\n"
"")
        self.spinBox_10.setAlignment(QtCore.Qt.AlignCenter)
        self.spinBox_10.setObjectName("spinBox_10")
        self.spinBox_11 = QtWidgets.QSpinBox(QueryTable4)
        self.spinBox_11.setGeometry(QtCore.QRect(370, 700, 131, 31))
        self.spinBox_11.setStyleSheet("background-color:rgb(255, 255, 255);\n"
"border:2px solid;\n"
"border-radius:10;\n"
"")
        self.spinBox_11.setAlignment(QtCore.Qt.AlignCenter)
        self.spinBox_11.setObjectName("spinBox_11")
        self.spinBox_18 = QtWidgets.QSpinBox(QueryTable4)
        self.spinBox_18.setGeometry(QtCore.QRect(1030, 140, 131, 31))
        self.spinBox_18.setStyleSheet("background-color:rgb(255, 255, 255);\n"
"border:2px solid;\n"
"border-radius:10;\n"
"")
        self.spinBox_18.setAlignment(QtCore.Qt.AlignCenter)
        self.spinBox_18.setObjectName("spinBox_18")
        self.textEdit_40 = QtWidgets.QTextEdit(QueryTable4)
        self.textEdit_40.setGeometry(QtCore.QRect(1170, 420, 151, 31))
        self.textEdit_40.setStyleSheet("background-color:rgb(255, 255, 255);\n"
"border:2px solid;\n"
"border-radius:10;\n"
"")
        self.textEdit_40.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.textEdit_40.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textEdit_40.setObjectName("textEdit_40")
        self.label_6 = QtWidgets.QLabel(QueryTable4)
        self.label_6.setGeometry(QtCore.QRect(20, 540, 241, 31))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_6.setStyleSheet("background-color: rgb(250, 250, 125);\n"
"border:2px solid;\n"
"border-radius:10;\n"
"")
        self.label_6.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.spinBox_14 = QtWidgets.QSpinBox(QueryTable4)
        self.spinBox_14.setGeometry(QtCore.QRect(370, 660, 131, 31))
        self.spinBox_14.setStyleSheet("background-color:rgb(255, 255, 255);\n"
"border:2px solid;\n"
"border-radius:10;\n"
"")
        self.spinBox_14.setAlignment(QtCore.Qt.AlignCenter)
        self.spinBox_14.setObjectName("spinBox_14")
        self.spinBox_4 = QtWidgets.QSpinBox(QueryTable4)
        self.spinBox_4.setGeometry(QtCore.QRect(370, 220, 131, 31))
        self.spinBox_4.setStyleSheet("background-color:rgb(255, 255, 255);\n"
"border:2px solid;\n"
"border-radius:10;\n"
"")
        self.spinBox_4.setAlignment(QtCore.Qt.AlignCenter)
        self.spinBox_4.setObjectName("spinBox_4")
        self.textEdit_46 = QtWidgets.QTextEdit(QueryTable4)
        self.textEdit_46.setGeometry(QtCore.QRect(680, 140, 341, 31))
        self.textEdit_46.setStyleSheet("background-color:rgb(255, 255, 255);\n"
"border:2px solid;\n"
"border-radius:10;\n"
"")
        self.textEdit_46.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textEdit_46.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textEdit_46.setObjectName("textEdit_46")
        self.spinBox_21 = QtWidgets.QSpinBox(QueryTable4)
        self.spinBox_21.setGeometry(QtCore.QRect(1030, 100, 131, 31))
        self.spinBox_21.setStyleSheet("background-color:rgb(255, 255, 255);\n"
"border:2px solid;\n"
"border-radius:10;\n"
"")
        self.spinBox_21.setAlignment(QtCore.Qt.AlignCenter)
        self.spinBox_21.setObjectName("spinBox_21")
        self.spinBox_25 = QtWidgets.QSpinBox(QueryTable4)
        self.spinBox_25.setGeometry(QtCore.QRect(1030, 180, 131, 31))
        self.spinBox_25.setStyleSheet("background-color:rgb(255, 255, 255);\n"
"border:2px solid;\n"
"border-radius:10;\n"
"")
        self.spinBox_25.setAlignment(QtCore.Qt.AlignCenter)
        self.spinBox_25.setObjectName("spinBox_25")
        self.label_7 = QtWidgets.QLabel(QueryTable4)
        self.label_7.setGeometry(QtCore.QRect(680, 260, 241, 31))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_7.setStyleSheet("background-color: rgb(250, 250, 125);\n"
"border:2px solid;\n"
"border-radius:10;\n"
"")
        self.label_7.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.textEdit_30 = QtWidgets.QTextEdit(QueryTable4)
        self.textEdit_30.setGeometry(QtCore.QRect(510, 700, 151, 31))
        self.textEdit_30.setStyleSheet("background-color:rgb(255, 255, 255);\n"
"border:2px solid;\n"
"border-radius:10;\n"
"")
        self.textEdit_30.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.textEdit_30.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textEdit_30.setObjectName("textEdit_30")
        self.textEdit_9 = QtWidgets.QTextEdit(QueryTable4)
        self.textEdit_9.setGeometry(QtCore.QRect(20, 220, 341, 31))
        self.textEdit_9.setStyleSheet("background-color:rgb(255, 255, 255);\n"
"border:2px solid;\n"
"border-radius:10;\n"
"")
        self.textEdit_9.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textEdit_9.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textEdit_9.setObjectName("textEdit_9")
        self.textEdit_16 = QtWidgets.QTextEdit(QueryTable4)
        self.textEdit_16.setGeometry(QtCore.QRect(20, 340, 341, 31))
        self.textEdit_16.setStyleSheet("background-color:rgb(255, 255, 255);\n"
"border:2px solid;\n"
"border-radius:10;\n"
"")
        self.textEdit_16.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textEdit_16.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textEdit_16.setObjectName("textEdit_16")
        self.textEdit_29 = QtWidgets.QTextEdit(QueryTable4)
        self.textEdit_29.setGeometry(QtCore.QRect(20, 620, 341, 31))
        self.textEdit_29.setStyleSheet("background-color:rgb(255, 255, 255);\n"
"border:2px solid;\n"
"border-radius:10;\n"
"")
        self.textEdit_29.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textEdit_29.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textEdit_29.setObjectName("textEdit_29")
        self.textEdit_14 = QtWidgets.QTextEdit(QueryTable4)
        self.textEdit_14.setGeometry(QtCore.QRect(510, 500, 151, 31))
        self.textEdit_14.setStyleSheet("background-color:rgb(255, 255, 255);\n"
"border:2px solid;\n"
"border-radius:10;\n"
"")
        self.textEdit_14.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.textEdit_14.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textEdit_14.setObjectName("textEdit_14")
        self.textEdit_25 = QtWidgets.QTextEdit(QueryTable4)
        self.textEdit_25.setGeometry(QtCore.QRect(20, 660, 341, 31))
        self.textEdit_25.setStyleSheet("background-color:rgb(255, 255, 255);\n"
"border:2px solid;\n"
"border-radius:10;\n"
"")
        self.textEdit_25.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textEdit_25.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textEdit_25.setObjectName("textEdit_25")
        self.spinBox_23 = QtWidgets.QSpinBox(QueryTable4)
        self.spinBox_23.setGeometry(QtCore.QRect(1030, 340, 131, 31))
        self.spinBox_23.setStyleSheet("background-color:rgb(255, 255, 255);\n"
"border:2px solid;\n"
"border-radius:10;\n"
"")
        self.spinBox_23.setAlignment(QtCore.Qt.AlignCenter)
        self.spinBox_23.setObjectName("spinBox_23")
        self.spinBox_15 = QtWidgets.QSpinBox(QueryTable4)
        self.spinBox_15.setGeometry(QtCore.QRect(370, 620, 131, 31))
        self.spinBox_15.setStyleSheet("background-color:rgb(255, 255, 255);\n"
"border:2px solid;\n"
"border-radius:10;\n"
"")
        self.spinBox_15.setAlignment(QtCore.Qt.AlignCenter)
        self.spinBox_15.setObjectName("spinBox_15")
        self.textEdit_49 = QtWidgets.QTextEdit(QueryTable4)
        self.textEdit_49.setGeometry(QtCore.QRect(930, 260, 391, 31))
        self.textEdit_49.setStyleSheet("background-color:rgb(255, 255, 255);\n"
"border:2px solid;\n"
"border-radius:10;\n"
"")
        self.textEdit_49.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.textEdit_49.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textEdit_49.setObjectName("textEdit_49")
        self.textEdit_7 = QtWidgets.QTextEdit(QueryTable4)
        self.textEdit_7.setGeometry(QtCore.QRect(20, 180, 341, 31))
        self.textEdit_7.setStyleSheet("background-color:rgb(255, 255, 255);\n"
"border:2px solid;\n"
"border-radius:10;\n"
"")
        self.textEdit_7.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textEdit_7.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textEdit_7.setObjectName("textEdit_7")
        self.spinBox_6 = QtWidgets.QSpinBox(QueryTable4)
        self.spinBox_6.setGeometry(QtCore.QRect(370, 460, 131, 31))
        self.spinBox_6.setStyleSheet("background-color:rgb(255, 255, 255);\n"
"border:2px solid;\n"
"border-radius:10;\n"
"")
        self.spinBox_6.setAlignment(QtCore.Qt.AlignCenter)
        self.spinBox_6.setObjectName("spinBox_6")
        self.spinBox_5 = QtWidgets.QSpinBox(QueryTable4)
        self.spinBox_5.setGeometry(QtCore.QRect(370, 260, 131, 31))
        self.spinBox_5.setStyleSheet("background-color:rgb(255, 255, 255);\n"
"border:2px solid;\n"
"border-radius:10;\n"
"")
        self.spinBox_5.setAlignment(QtCore.Qt.AlignCenter)
        self.spinBox_5.setObjectName("spinBox_5")
        self.spinBox_16 = QtWidgets.QSpinBox(QueryTable4)
        self.spinBox_16.setGeometry(QtCore.QRect(1030, 60, 131, 31))
        self.spinBox_16.setStyleSheet("background-color:rgb(255, 255, 255);\n"
"border:2px solid;\n"
"border-radius:10;\n"
"")
        self.spinBox_16.setAlignment(QtCore.Qt.AlignCenter)
        self.spinBox_16.setObjectName("spinBox_16")
        self.textEdit_33 = QtWidgets.QTextEdit(QueryTable4)
        self.textEdit_33.setGeometry(QtCore.QRect(20, 740, 341, 31))
        self.textEdit_33.setStyleSheet("background-color:rgb(255, 255, 255);\n"
"border:2px solid;\n"
"border-radius:10;\n"
"")
        self.textEdit_33.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textEdit_33.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textEdit_33.setObjectName("textEdit_33")
        self.textEdit_18 = QtWidgets.QTextEdit(QueryTable4)
        self.textEdit_18.setGeometry(QtCore.QRect(510, 420, 151, 31))
        self.textEdit_18.setStyleSheet("background-color:rgb(255, 255, 255);\n"
"border:2px solid;\n"
"border-radius:10;\n"
"")
        self.textEdit_18.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.textEdit_18.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textEdit_18.setObjectName("textEdit_18")
        self.spinBox_20 = QtWidgets.QSpinBox(QueryTable4)
        self.spinBox_20.setGeometry(QtCore.QRect(1030, 460, 131, 31))
        self.spinBox_20.setStyleSheet("background-color:rgb(255, 255, 255);\n"
"border:2px solid;\n"
"border-radius:10;\n"
"")
        self.spinBox_20.setAlignment(QtCore.Qt.AlignCenter)
        self.spinBox_20.setObjectName("spinBox_20")
        self.label_3 = QtWidgets.QLabel(QueryTable4)
        self.label_3.setGeometry(QtCore.QRect(370, 60, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_3.setStyleSheet("background-color: rgb(250, 250, 125);\n"
"border:2px solid;\n"
"border-radius:10;\n"
"")
        self.label_3.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.textEdit_36 = QtWidgets.QTextEdit(QueryTable4)
        self.textEdit_36.setGeometry(QtCore.QRect(1170, 340, 151, 31))
        self.textEdit_36.setStyleSheet("background-color:rgb(255, 255, 255);\n"
"border:2px solid;\n"
"border-radius:10;\n"
"")
        self.textEdit_36.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.textEdit_36.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textEdit_36.setObjectName("textEdit_36")
        self.spinBox_2 = QtWidgets.QSpinBox(QueryTable4)
        self.spinBox_2.setGeometry(QtCore.QRect(370, 140, 131, 31))
        self.spinBox_2.setStyleSheet("background-color:rgb(255, 255, 255);\n"
"border:2px solid;\n"
"border-radius:10;\n"
"")
        self.spinBox_2.setAlignment(QtCore.Qt.AlignCenter)
        self.spinBox_2.setObjectName("spinBox_2")
        self.textEdit_45 = QtWidgets.QTextEdit(QueryTable4)
        self.textEdit_45.setGeometry(QtCore.QRect(1170, 100, 151, 31))
        self.textEdit_45.setStyleSheet("background-color:rgb(255, 255, 255);\n"
"border:2px solid;\n"
"border-radius:10;\n"
"")
        self.textEdit_45.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.textEdit_45.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textEdit_45.setObjectName("textEdit_45")
        self.textEdit_15 = QtWidgets.QTextEdit(QueryTable4)
        self.textEdit_15.setGeometry(QtCore.QRect(510, 340, 151, 31))
        self.textEdit_15.setStyleSheet("background-color:rgb(255, 255, 255);\n"
"border:2px solid;\n"
"border-radius:10;\n"
"")
        self.textEdit_15.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.textEdit_15.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textEdit_15.setObjectName("textEdit_15")
        self.textEdit_27 = QtWidgets.QTextEdit(QueryTable4)
        self.textEdit_27.setGeometry(QtCore.QRect(510, 660, 151, 31))
        self.textEdit_27.setStyleSheet("background-color:rgb(255, 255, 255);\n"
"border:2px solid;\n"
"border-radius:10;\n"
"")
        self.textEdit_27.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.textEdit_27.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textEdit_27.setObjectName("textEdit_27")
        self.textEdit_22 = QtWidgets.QTextEdit(QueryTable4)
        self.textEdit_22.setGeometry(QtCore.QRect(510, 460, 151, 31))
        self.textEdit_22.setStyleSheet("background-color:rgb(255, 255, 255);\n"
"border:2px solid;\n"
"border-radius:10;\n"
"")
        self.textEdit_22.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.textEdit_22.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textEdit_22.setObjectName("textEdit_22")
        self.textEdit_17 = QtWidgets.QTextEdit(QueryTable4)
        self.textEdit_17.setGeometry(QtCore.QRect(20, 460, 341, 31))
        self.textEdit_17.setStyleSheet("background-color:rgb(255, 255, 255);\n"
"border:2px solid;\n"
"border-radius:10;\n"
"")
        self.textEdit_17.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textEdit_17.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textEdit_17.setObjectName("textEdit_17")
        self.textEdit_21 = QtWidgets.QTextEdit(QueryTable4)
        self.textEdit_21.setGeometry(QtCore.QRect(20, 500, 341, 31))
        self.textEdit_21.setStyleSheet("background-color:rgb(255, 255, 255);\n"
"border:2px solid;\n"
"border-radius:10;\n"
"")
        self.textEdit_21.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textEdit_21.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textEdit_21.setObjectName("textEdit_21")
        self.spinBox_24 = QtWidgets.QSpinBox(QueryTable4)
        self.spinBox_24.setGeometry(QtCore.QRect(1030, 380, 131, 31))
        self.spinBox_24.setStyleSheet("background-color:rgb(255, 255, 255);\n"
"border:2px solid;\n"
"border-radius:10;\n"
"")
        self.spinBox_24.setAlignment(QtCore.Qt.AlignCenter)
        self.spinBox_24.setObjectName("spinBox_24")
        self.spinBox_19 = QtWidgets.QSpinBox(QueryTable4)
        self.spinBox_19.setGeometry(QtCore.QRect(1030, 220, 131, 31))
        self.spinBox_19.setStyleSheet("background-color:rgb(255, 255, 255);\n"
"border:2px solid;\n"
"border-radius:10;\n"
"")
        self.spinBox_19.setAlignment(QtCore.Qt.AlignCenter)
        self.spinBox_19.setObjectName("spinBox_19")
        self.textEdit_55 = QtWidgets.QTextEdit(QueryTable4)
        self.textEdit_55.setGeometry(QtCore.QRect(680, 60, 341, 31))
        self.textEdit_55.setStyleSheet("background-color:rgb(255, 255, 255);\n"
"border:2px solid;\n"
"border-radius:10;\n"
"")
        self.textEdit_55.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textEdit_55.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textEdit_55.setObjectName("textEdit_55")
        self.textEdit_28 = QtWidgets.QTextEdit(QueryTable4)
        self.textEdit_28.setGeometry(QtCore.QRect(510, 580, 151, 31))
        self.textEdit_28.setStyleSheet("background-color:rgb(255, 255, 255);\n"
"border:2px solid;\n"
"border-radius:10;\n"
"")
        self.textEdit_28.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.textEdit_28.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textEdit_28.setObjectName("textEdit_28")
        self.label_5 = QtWidgets.QLabel(QueryTable4)
        self.label_5.setGeometry(QtCore.QRect(20, 300, 241, 31))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_5.setStyleSheet("background-color: rgb(250, 250, 125);\n"
"border:2px solid;\n"
"border-radius:10;\n"
"")
        self.label_5.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.textEdit_39 = QtWidgets.QTextEdit(QueryTable4)
        self.textEdit_39.setGeometry(QtCore.QRect(680, 380, 341, 31))
        self.textEdit_39.setStyleSheet("background-color:rgb(255, 255, 255);\n"
"border:2px solid;\n"
"border-radius:10;\n"
"")
        self.textEdit_39.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textEdit_39.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textEdit_39.setObjectName("textEdit_39")
        self.textEdit_4 = QtWidgets.QTextEdit(QueryTable4)
        self.textEdit_4.setGeometry(QtCore.QRect(510, 100, 151, 31))
        self.textEdit_4.setStyleSheet("background-color:rgb(255, 255, 255);\n"
"border:2px solid;\n"
"border-radius:10;\n"
"")
        self.textEdit_4.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.textEdit_4.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textEdit_4.setObjectName("textEdit_4")
        self.textEdit_41 = QtWidgets.QTextEdit(QueryTable4)
        self.textEdit_41.setGeometry(QtCore.QRect(1170, 140, 151, 31))
        self.textEdit_41.setStyleSheet("background-color:rgb(255, 255, 255);\n"
"border:2px solid;\n"
"border-radius:10;\n"
"")
        self.textEdit_41.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.textEdit_41.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textEdit_41.setObjectName("textEdit_41")
        self.textEdit_35 = QtWidgets.QTextEdit(QueryTable4)
        self.textEdit_35.setGeometry(QtCore.QRect(1170, 300, 151, 31))
        self.textEdit_35.setStyleSheet("background-color:rgb(255, 255, 255);\n"
"border:2px solid;\n"
"border-radius:10;\n"
"")
        self.textEdit_35.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.textEdit_35.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textEdit_35.setObjectName("textEdit_35")
        self.textEdit_5 = QtWidgets.QTextEdit(QueryTable4)
        self.textEdit_5.setGeometry(QtCore.QRect(510, 140, 151, 31))
        self.textEdit_5.setStyleSheet("background-color:rgb(255, 255, 255);\n"
"border:2px solid;\n"
"border-radius:10;\n"
"")
        self.textEdit_5.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.textEdit_5.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textEdit_5.setObjectName("textEdit_5")
        self.textEdit_52 = QtWidgets.QTextEdit(QueryTable4)
        self.textEdit_52.setGeometry(QtCore.QRect(680, 100, 341, 31))
        self.textEdit_52.setStyleSheet("background-color:rgb(255, 255, 255);\n"
"border:2px solid;\n"
"border-radius:10;\n"
"")
        self.textEdit_52.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textEdit_52.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textEdit_52.setObjectName("textEdit_52")
        self.textEdit_11 = QtWidgets.QTextEdit(QueryTable4)
        self.textEdit_11.setGeometry(QtCore.QRect(20, 260, 341, 31))
        self.textEdit_11.setStyleSheet("background-color:rgb(255, 255, 255);\n"
"border:2px solid;\n"
"border-radius:10;\n"
"")
        self.textEdit_11.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textEdit_11.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textEdit_11.setObjectName("textEdit_11")
        self.textEdit_32 = QtWidgets.QTextEdit(QueryTable4)
        self.textEdit_32.setGeometry(QtCore.QRect(510, 620, 151, 31))
        self.textEdit_32.setStyleSheet("background-color:rgb(255, 255, 255);\n"
"border:2px solid;\n"
"border-radius:10;\n"
"")
        self.textEdit_32.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.textEdit_32.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textEdit_32.setObjectName("textEdit_32")
        self.label_2 = QtWidgets.QLabel(QueryTable4)
        self.label_2.setGeometry(QtCore.QRect(20, 60, 341, 31))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_2.setStyleSheet("background-color: rgb(250, 250, 125);\n"
"border:2px solid;\n"
"border-radius:10;\n"
"")
        self.label_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.textEdit_51 = QtWidgets.QTextEdit(QueryTable4)
        self.textEdit_51.setGeometry(QtCore.QRect(1170, 460, 151, 31))
        self.textEdit_51.setStyleSheet("background-color:rgb(255, 255, 255);\n"
"border:2px solid;\n"
"border-radius:10;\n"
"")
        self.textEdit_51.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.textEdit_51.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textEdit_51.setObjectName("textEdit_51")
        self.spinBox_8 = QtWidgets.QSpinBox(QueryTable4)
        self.spinBox_8.setGeometry(QtCore.QRect(370, 500, 131, 31))
        self.spinBox_8.setStyleSheet("background-color:rgb(255, 255, 255);\n"
"border:2px solid;\n"
"border-radius:10;\n"
"")
        self.spinBox_8.setAlignment(QtCore.Qt.AlignCenter)
        self.spinBox_8.setObjectName("spinBox_8")
        self.spinBox_13 = QtWidgets.QSpinBox(QueryTable4)
        self.spinBox_13.setGeometry(QtCore.QRect(370, 740, 131, 31))
        self.spinBox_13.setStyleSheet("background-color:rgb(255, 255, 255);\n"
"border:2px solid;\n"
"border-radius:10;\n"
"")
        self.spinBox_13.setAlignment(QtCore.Qt.AlignCenter)
        self.spinBox_13.setObjectName("spinBox_13")
        self.label_4 = QtWidgets.QLabel(QueryTable4)
        self.label_4.setGeometry(QtCore.QRect(510, 60, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_4.setStyleSheet("background-color: rgb(250, 250, 125);\n"
"border:2px solid;\n"
"border-radius:10;\n"
"")
        self.label_4.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.textEdit_10 = QtWidgets.QTextEdit(QueryTable4)
        self.textEdit_10.setGeometry(QtCore.QRect(510, 260, 151, 31))
        self.textEdit_10.setStyleSheet("background-color:rgb(255, 255, 255);\n"
"border:2px solid;\n"
"border-radius:10;\n"
"")
        self.textEdit_10.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.textEdit_10.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textEdit_10.setObjectName("textEdit_10")
        self.textEdit_8 = QtWidgets.QTextEdit(QueryTable4)
        self.textEdit_8.setGeometry(QtCore.QRect(510, 220, 151, 31))
        self.textEdit_8.setStyleSheet("background-color:rgb(255, 255, 255);\n"
"border:2px solid;\n"
"border-radius:10;\n"
"")
        self.textEdit_8.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.textEdit_8.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textEdit_8.setObjectName("textEdit_8")
        self.textEdit_12 = QtWidgets.QTextEdit(QueryTable4)
        self.textEdit_12.setGeometry(QtCore.QRect(270, 300, 391, 31))
        self.textEdit_12.setStyleSheet("background-color:rgb(255, 255, 255);\n"
"border:2px solid;\n"
"border-radius:10;\n"
"")
        self.textEdit_12.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.textEdit_12.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textEdit_12.setObjectName("textEdit_12")
        self.textEdit_6 = QtWidgets.QTextEdit(QueryTable4)
        self.textEdit_6.setGeometry(QtCore.QRect(510, 180, 151, 31))
        self.textEdit_6.setStyleSheet("background-color:rgb(255, 255, 255);\n"
"border:2px solid;\n"
"border-radius:10;\n"
"")
        self.textEdit_6.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.textEdit_6.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textEdit_6.setObjectName("textEdit_6")
        self.spinBox_12 = QtWidgets.QSpinBox(QueryTable4)
        self.spinBox_12.setGeometry(QtCore.QRect(370, 580, 131, 31))
        self.spinBox_12.setStyleSheet("background-color:rgb(255, 255, 255);\n"
"border:2px solid;\n"
"border-radius:10;\n"
"")
        self.spinBox_12.setAlignment(QtCore.Qt.AlignCenter)
        self.spinBox_12.setObjectName("spinBox_12")
        self.textEdit_48 = QtWidgets.QTextEdit(QueryTable4)
        self.textEdit_48.setGeometry(QtCore.QRect(680, 460, 341, 31))
        self.textEdit_48.setStyleSheet("background-color:rgb(255, 255, 255);\n"
"border:2px solid;\n"
"border-radius:10;\n"
"")
        self.textEdit_48.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textEdit_48.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textEdit_48.setObjectName("textEdit_48")
        self.pushButton_3 = QtWidgets.QPushButton(QueryTable4)
        self.pushButton_3.setGeometry(QtCore.QRect(990, 740, 93, 28))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setStyleSheet("background-color: rgb(250, 250, 125);\n"
"border-radius: 30px;\n"
"border: 1.5px solid")
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton = QtWidgets.QPushButton(QueryTable4)
        self.pushButton.setGeometry(QtCore.QRect(1100, 740, 111, 28))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("background-color: rgb(250, 250, 125);\n"
"border-radius: 30px;\n"
"border: 1.5px solid")
        self.pushButton.setObjectName("pushButton")

        self.retranslateUi(QueryTable4)
        QtCore.QMetaObject.connectSlotsByName(QueryTable4)

    def retranslateUi(self, QueryTable4):
        _translate = QtCore.QCoreApplication.translate
        QueryTable4.setWindowTitle(_translate("QueryTable4", "Dialog"))
        self.label_8.setText(_translate("QueryTable4", "Запрос:"))
        self.label.setText(_translate("QueryTable4", "Запрос:"))
        self.label_6.setText(_translate("QueryTable4", "Запрос:"))
        self.label_7.setText(_translate("QueryTable4", "Запрос:"))
        self.label_3.setText(_translate("QueryTable4", "Оценка(1-10):"))
        self.label_5.setText(_translate("QueryTable4", "Запрос:"))
        self.label_2.setText(_translate("QueryTable4", "Источник:"))
        self.label_4.setText(_translate("QueryTable4", "Тип ресурса:"))
        self.pushButton_3.setText(_translate("QueryTable4", "Сохранить"))
        self.pushButton.setText(_translate("QueryTable4", "На главную "))
