# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'QueryTable1.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_QueryTable(object):
    def setupUi(self, QueryTable1):
        QueryTable1.setObjectName("QueryTable1")
        QueryTable1.resize(1332, 827)
        QueryTable1.setStyleSheet("background-color:rgb(174, 221, 242)")
        self.spinBox_10 = QtWidgets.QSpinBox(QueryTable1)
        self.spinBox_10.setGeometry(QtCore.QRect(370, 500, 131, 31))
        self.spinBox_10.setStyleSheet("background-color:rgb(255, 255, 255);\n"
"border:2px solid;\n"
"border-radius:10;\n"
"")
        self.spinBox_10.setAlignment(QtCore.Qt.AlignCenter)
        self.spinBox_10.setObjectName("spinBox_10")
        self.textEdit_type_13 = QtWidgets.QTextEdit(QueryTable1)
        self.textEdit_type_13.setGeometry(QtCore.QRect(510, 660, 151, 31))
        self.textEdit_type_13.setStyleSheet("background-color:rgb(255, 255, 255);\n"
"border:2px solid;\n"
"border-radius:10;\n"
"")
        self.textEdit_type_13.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.textEdit_type_13.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textEdit_type_13.setObjectName("textEdit_type_13")
        self.textEdit_source_12 = QtWidgets.QTextEdit(QueryTable1)
        self.textEdit_source_12.setGeometry(QtCore.QRect(20, 620, 341, 31))
        self.textEdit_source_12.setStyleSheet("background-color:rgb(255, 255, 255);\n"
"border:2px solid;\n"
"border-radius:10;\n"
"")
        self.textEdit_source_12.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textEdit_source_12.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textEdit_source_12.setObjectName("textEdit_source_12")
        self.textEdit_source_7 = QtWidgets.QTextEdit(QueryTable1)
        self.textEdit_source_7.setGeometry(QtCore.QRect(20, 380, 341, 31))
        self.textEdit_source_7.setStyleSheet("background-color:rgb(255, 255, 255);\n"
"border:2px solid;\n"
"border-radius:10;\n"
"")
        self.textEdit_source_7.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textEdit_source_7.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textEdit_source_7.setObjectName("textEdit_source_7")
        self.textEdit_source_2 = QtWidgets.QTextEdit(QueryTable1)
        self.textEdit_source_2.setGeometry(QtCore.QRect(20, 140, 341, 31))
        self.textEdit_source_2.setStyleSheet("background-color:rgb(255, 255, 255);\n"
"border:2px solid;\n"
"border-radius:10;\n"
"")
        self.textEdit_source_2.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textEdit_source_2.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textEdit_source_2.setObjectName("textEdit_source_2")
        self.textEdit_type_8 = QtWidgets.QTextEdit(QueryTable1)
        self.textEdit_type_8.setGeometry(QtCore.QRect(510, 420, 151, 31))
        self.textEdit_type_8.setStyleSheet("background-color:rgb(255, 255, 255);\n"
"border:2px solid;\n"
"border-radius:10;\n"
"")
        self.textEdit_type_8.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.textEdit_type_8.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textEdit_type_8.setObjectName("textEdit_type_8")
        self.textEdit_type_5 = QtWidgets.QTextEdit(QueryTable1)
        self.textEdit_type_5.setGeometry(QtCore.QRect(510, 260, 151, 31))
        self.textEdit_type_5.setStyleSheet("background-color:rgb(255, 255, 255);\n"
"border:2px solid;\n"
"border-radius:10;\n"
"")
        self.textEdit_type_5.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.textEdit_type_5.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textEdit_type_5.setObjectName("textEdit_type_5")
        self.textEdit_source_10 = QtWidgets.QTextEdit(QueryTable1)
        self.textEdit_source_10.setGeometry(QtCore.QRect(20, 500, 341, 31))
        self.textEdit_source_10.setStyleSheet("background-color:rgb(255, 255, 255);\n"
"border:2px solid;\n"
"border-radius:10;\n"
"")
        self.textEdit_source_10.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textEdit_source_10.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textEdit_source_10.setObjectName("textEdit_source_10")
        self.spinBox_9 = QtWidgets.QSpinBox(QueryTable1)
        self.spinBox_9.setGeometry(QtCore.QRect(370, 460, 131, 31))
        self.spinBox_9.setStyleSheet("background-color:rgb(255, 255, 255);\n"
"border:2px solid;\n"
"border-radius:10;\n"
"")
        self.spinBox_9.setAlignment(QtCore.Qt.AlignCenter)
        self.spinBox_9.setObjectName("spinBox_9")
        self.textEditZapros3 = QtWidgets.QTextEdit(QueryTable1)
        self.textEditZapros3.setGeometry(QtCore.QRect(270, 540, 391, 31))
        self.textEditZapros3.setStyleSheet("background-color:rgb(255, 255, 255);\n"
"border:2px solid;\n"
"border-radius:10;\n"
"")
        self.textEditZapros3.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.textEditZapros3.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textEditZapros3.setObjectName("textEditZapros3")
        self.label_5 = QtWidgets.QLabel(QueryTable1)
        self.label_5.setGeometry(QtCore.QRect(20, 300, 241, 31))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_5.setStyleSheet("background-color: rgb(250, 250, 125);\n"
"border:2px solid;\n"
"border-radius:10;\n"
"")
        self.label_5.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.spinBox_11 = QtWidgets.QSpinBox(QueryTable1)
        self.spinBox_11.setGeometry(QtCore.QRect(370, 580, 131, 31))
        self.spinBox_11.setStyleSheet("background-color:rgb(255, 255, 255);\n"
"border:2px solid;\n"
"border-radius:10;\n"
"")
        self.spinBox_11.setAlignment(QtCore.Qt.AlignCenter)
        self.spinBox_11.setObjectName("spinBox_11")
        self.textEdit_source_1 = QtWidgets.QTextEdit(QueryTable1)
        self.textEdit_source_1.setGeometry(QtCore.QRect(20, 100, 341, 31))
        self.textEdit_source_1.setStyleSheet("background-color:rgb(255, 255, 255);\n"
"border:2px solid;\n"
"border-radius:10;\n"
"")
        self.textEdit_source_1.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textEdit_source_1.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textEdit_source_1.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.textEdit_source_1.setObjectName("textEdit_source_1")
        self.textEdit_source_14 = QtWidgets.QTextEdit(QueryTable1)
        self.textEdit_source_14.setGeometry(QtCore.QRect(20, 700, 341, 31))
        self.textEdit_source_14.setStyleSheet("background-color:rgb(255, 255, 255);\n"
"border:2px solid;\n"
"border-radius:10;\n"
"")
        self.textEdit_source_14.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textEdit_source_14.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textEdit_source_14.setObjectName("textEdit_source_14")
        self.label_4 = QtWidgets.QLabel(QueryTable1)
        self.label_4.setGeometry(QtCore.QRect(510, 60, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_4.setStyleSheet("background-color: rgb(250, 250, 125);\n"
"border:2px solid;\n"
"border-radius:10;\n"
"")
        self.label_4.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.textEdit_type_14 = QtWidgets.QTextEdit(QueryTable1)
        self.textEdit_type_14.setGeometry(QtCore.QRect(510, 700, 151, 31))
        self.textEdit_type_14.setStyleSheet("background-color:rgb(255, 255, 255);\n"
"border:2px solid;\n"
"border-radius:10;\n"
"")
        self.textEdit_type_14.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.textEdit_type_14.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textEdit_type_14.setObjectName("textEdit_type_14")
        self.textEdit_type_12 = QtWidgets.QTextEdit(QueryTable1)
        self.textEdit_type_12.setGeometry(QtCore.QRect(510, 620, 151, 31))
        self.textEdit_type_12.setStyleSheet("background-color:rgb(255, 255, 255);\n"
"border:2px solid;\n"
"border-radius:10;\n"
"")
        self.textEdit_type_12.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.textEdit_type_12.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textEdit_type_12.setObjectName("textEdit_type_12")
        self.spinBox_15 = QtWidgets.QSpinBox(QueryTable1)
        self.spinBox_15.setGeometry(QtCore.QRect(370, 740, 131, 31))
        self.spinBox_15.setStyleSheet("background-color:rgb(255, 255, 255);\n"
"border:2px solid;\n"
"border-radius:10;\n"
"")
        self.spinBox_15.setAlignment(QtCore.Qt.AlignCenter)
        self.spinBox_15.setObjectName("spinBox_15")
        self.label_6 = QtWidgets.QLabel(QueryTable1)
        self.label_6.setGeometry(QtCore.QRect(20, 540, 241, 31))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_6.setStyleSheet("background-color: rgb(250, 250, 125);\n"
"border:2px solid;\n"
"border-radius:10;\n"
"")
        self.label_6.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.textEditZapros1 = QtWidgets.QTextEdit(QueryTable1)
        self.textEditZapros1.setGeometry(QtCore.QRect(270, 20, 391, 31))
        self.textEditZapros1.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.textEditZapros1.setStyleSheet("background-color:rgb(255, 255, 255);\n"
"border:2px solid;\n"
"border-radius:10;\n"
"")
        self.textEditZapros1.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.textEditZapros1.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textEditZapros1.setObjectName("textEditZapros1")
        self.textEdit_type_9 = QtWidgets.QTextEdit(QueryTable1)
        self.textEdit_type_9.setGeometry(QtCore.QRect(510, 460, 151, 31))
        self.textEdit_type_9.setStyleSheet("background-color:rgb(255, 255, 255);\n"
"border:2px solid;\n"
"border-radius:10;\n"
"")
        self.textEdit_type_9.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.textEdit_type_9.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textEdit_type_9.setObjectName("textEdit_type_9")
        self.spinBox_2 = QtWidgets.QSpinBox(QueryTable1)
        self.spinBox_2.setGeometry(QtCore.QRect(370, 140, 131, 31))
        self.spinBox_2.setStyleSheet("background-color:rgb(255, 255, 255);\n"
"border:2px solid;\n"
"border-radius:10;\n"
"")
        self.spinBox_2.setAlignment(QtCore.Qt.AlignCenter)
        self.spinBox_2.setObjectName("spinBox_2")
        self.spinBox_3 = QtWidgets.QSpinBox(QueryTable1)
        self.spinBox_3.setGeometry(QtCore.QRect(370, 180, 131, 31))
        self.spinBox_3.setStyleSheet("background-color:rgb(255, 255, 255);\n"
"border:2px solid;\n"
"border-radius:10;\n"
"")
        self.spinBox_3.setAlignment(QtCore.Qt.AlignCenter)
        self.spinBox_3.setObjectName("spinBox_3")
        self.textEdit_type_15 = QtWidgets.QTextEdit(QueryTable1)
        self.textEdit_type_15.setGeometry(QtCore.QRect(510, 740, 151, 31))
        self.textEdit_type_15.setStyleSheet("background-color:rgb(255, 255, 255);\n"
"border:2px solid;\n"
"border-radius:10;\n"
"")
        self.textEdit_type_15.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.textEdit_type_15.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textEdit_type_15.setObjectName("textEdit_type_15")
        self.textEdit_source_9 = QtWidgets.QTextEdit(QueryTable1)
        self.textEdit_source_9.setGeometry(QtCore.QRect(20, 460, 341, 31))
        self.textEdit_source_9.setStyleSheet("background-color:rgb(255, 255, 255);\n"
"border:2px solid;\n"
"border-radius:10;\n"
"")
        self.textEdit_source_9.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textEdit_source_9.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textEdit_source_9.setObjectName("textEdit_source_9")
        self.textEdit_type_3 = QtWidgets.QTextEdit(QueryTable1)
        self.textEdit_type_3.setGeometry(QtCore.QRect(510, 180, 151, 31))
        self.textEdit_type_3.setStyleSheet("background-color:rgb(255, 255, 255);\n"
"border:2px solid;\n"
"border-radius:10;\n"
"")
        self.textEdit_type_3.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.textEdit_type_3.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textEdit_type_3.setObjectName("textEdit_type_3")
        self.label_3 = QtWidgets.QLabel(QueryTable1)
        self.label_3.setGeometry(QtCore.QRect(370, 60, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_3.setStyleSheet("background-color: rgb(250, 250, 125);\n"
"border:2px solid;\n"
"border-radius:10;\n"
"")
        self.label_3.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.textEdit_source_5 = QtWidgets.QTextEdit(QueryTable1)
        self.textEdit_source_5.setGeometry(QtCore.QRect(20, 260, 341, 31))
        self.textEdit_source_5.setStyleSheet("background-color:rgb(255, 255, 255);\n"
"border:2px solid;\n"
"border-radius:10;\n"
"")
        self.textEdit_source_5.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textEdit_source_5.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textEdit_source_5.setObjectName("textEdit_source_5")
        self.textEdit_source_13 = QtWidgets.QTextEdit(QueryTable1)
        self.textEdit_source_13.setGeometry(QtCore.QRect(20, 660, 341, 31))
        self.textEdit_source_13.setStyleSheet("background-color:rgb(255, 255, 255);\n"
"border:2px solid;\n"
"border-radius:10;\n"
"")
        self.textEdit_source_13.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textEdit_source_13.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textEdit_source_13.setObjectName("textEdit_source_13")
        self.spinBox_5 = QtWidgets.QSpinBox(QueryTable1)
        self.spinBox_5.setGeometry(QtCore.QRect(370, 260, 131, 31))
        self.spinBox_5.setStyleSheet("background-color:rgb(255, 255, 255);\n"
"border:2px solid;\n"
"border-radius:10;\n"
"")
        self.spinBox_5.setAlignment(QtCore.Qt.AlignCenter)
        self.spinBox_5.setObjectName("spinBox_5")
        self.spinBox_7 = QtWidgets.QSpinBox(QueryTable1)
        self.spinBox_7.setGeometry(QtCore.QRect(370, 380, 131, 31))
        self.spinBox_7.setStyleSheet("background-color:rgb(255, 255, 255);\n"
"border:2px solid;\n"
"border-radius:10;\n"
"")
        self.spinBox_7.setAlignment(QtCore.Qt.AlignCenter)
        self.spinBox_7.setObjectName("spinBox_7")
        self.textEdit_source_11 = QtWidgets.QTextEdit(QueryTable1)
        self.textEdit_source_11.setGeometry(QtCore.QRect(20, 580, 341, 31))
        self.textEdit_source_11.setStyleSheet("background-color:rgb(255, 255, 255);\n"
"border:2px solid;\n"
"border-radius:10;\n"
"")
        self.textEdit_source_11.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textEdit_source_11.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textEdit_source_11.setObjectName("textEdit_source_11")
        self.spinBox_12 = QtWidgets.QSpinBox(QueryTable1)
        self.spinBox_12.setGeometry(QtCore.QRect(370, 620, 131, 31))
        self.spinBox_12.setStyleSheet("background-color:rgb(255, 255, 255);\n"
"border:2px solid;\n"
"border-radius:10;\n"
"")
        self.spinBox_12.setAlignment(QtCore.Qt.AlignCenter)
        self.spinBox_12.setObjectName("spinBox_12")
        self.textEdit_type_6 = QtWidgets.QTextEdit(QueryTable1)
        self.textEdit_type_6.setGeometry(QtCore.QRect(510, 340, 151, 31))
        self.textEdit_type_6.setStyleSheet("background-color:rgb(255, 255, 255);\n"
"border:2px solid;\n"
"border-radius:10;\n"
"")
        self.textEdit_type_6.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.textEdit_type_6.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textEdit_type_6.setObjectName("textEdit_type_6")
        self.spinBox_13 = QtWidgets.QSpinBox(QueryTable1)
        self.spinBox_13.setGeometry(QtCore.QRect(370, 660, 131, 31))
        self.spinBox_13.setStyleSheet("background-color:rgb(255, 255, 255);\n"
"border:2px solid;\n"
"border-radius:10;\n"
"")
        self.spinBox_13.setAlignment(QtCore.Qt.AlignCenter)
        self.spinBox_13.setObjectName("spinBox_13")
        self.textEdit_type_4 = QtWidgets.QTextEdit(QueryTable1)
        self.textEdit_type_4.setGeometry(QtCore.QRect(510, 220, 151, 31))
        self.textEdit_type_4.setStyleSheet("background-color:rgb(255, 255, 255);\n"
"border:2px solid;\n"
"border-radius:10;\n"
"")
        self.textEdit_type_4.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.textEdit_type_4.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textEdit_type_4.setObjectName("textEdit_type_4")
        self.spinBox_6 = QtWidgets.QSpinBox(QueryTable1)
        self.spinBox_6.setGeometry(QtCore.QRect(370, 340, 131, 31))
        self.spinBox_6.setStyleSheet("background-color:rgb(255, 255, 255);\n"
"border:2px solid;\n"
"border-radius:10;\n"
"")
        self.spinBox_6.setAlignment(QtCore.Qt.AlignCenter)
        self.spinBox_6.setObjectName("spinBox_6")
        self.spinBox_4 = QtWidgets.QSpinBox(QueryTable1)
        self.spinBox_4.setGeometry(QtCore.QRect(370, 220, 131, 31))
        self.spinBox_4.setStyleSheet("background-color:rgb(255, 255, 255);\n"
"border:2px solid;\n"
"border-radius:10;\n"
"")
        self.spinBox_4.setAlignment(QtCore.Qt.AlignCenter)
        self.spinBox_4.setObjectName("spinBox_4")
        self.textEdit_type_10 = QtWidgets.QTextEdit(QueryTable1)
        self.textEdit_type_10.setGeometry(QtCore.QRect(510, 500, 151, 31))
        self.textEdit_type_10.setStyleSheet("background-color:rgb(255, 255, 255);\n"
"border:2px solid;\n"
"border-radius:10;\n"
"")
        self.textEdit_type_10.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.textEdit_type_10.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textEdit_type_10.setObjectName("textEdit_type_10")
        self.textEdit_source_6 = QtWidgets.QTextEdit(QueryTable1)
        self.textEdit_source_6.setGeometry(QtCore.QRect(20, 340, 341, 31))
        self.textEdit_source_6.setStyleSheet("background-color:rgb(255, 255, 255);\n"
"border:2px solid;\n"
"border-radius:10;\n"
"")
        self.textEdit_source_6.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textEdit_source_6.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textEdit_source_6.setObjectName("textEdit_source_6")
        self.textEdit_source_8 = QtWidgets.QTextEdit(QueryTable1)
        self.textEdit_source_8.setGeometry(QtCore.QRect(20, 420, 341, 31))
        self.textEdit_source_8.setStyleSheet("background-color:rgb(255, 255, 255);\n"
"border:2px solid;\n"
"border-radius:10;\n"
"")
        self.textEdit_source_8.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textEdit_source_8.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textEdit_source_8.setObjectName("textEdit_source_8")
        self.textEdit_type_2 = QtWidgets.QTextEdit(QueryTable1)
        self.textEdit_type_2.setGeometry(QtCore.QRect(510, 140, 151, 31))
        self.textEdit_type_2.setStyleSheet("background-color:rgb(255, 255, 255);\n"
"border:2px solid;\n"
"border-radius:10;\n"
"")
        self.textEdit_type_2.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.textEdit_type_2.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textEdit_type_2.setObjectName("textEdit_type_2")
        self.textEdit_source_4 = QtWidgets.QTextEdit(QueryTable1)
        self.textEdit_source_4.setGeometry(QtCore.QRect(20, 220, 341, 31))
        self.textEdit_source_4.setStyleSheet("background-color:rgb(255, 255, 255);\n"
"border:2px solid;\n"
"border-radius:10;\n"
"")
        self.textEdit_source_4.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textEdit_source_4.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textEdit_source_4.setObjectName("textEdit_source_4")
        self.textEdit_type_1 = QtWidgets.QTextEdit(QueryTable1)
        self.textEdit_type_1.setGeometry(QtCore.QRect(510, 100, 151, 31))
        self.textEdit_type_1.setStyleSheet("background-color:rgb(255, 255, 255);\n"
"border:2px solid;\n"
"border-radius:10;\n"
"")
        self.textEdit_type_1.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.textEdit_type_1.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textEdit_type_1.setObjectName("textEdit_type_1")
        self.spinBox_14 = QtWidgets.QSpinBox(QueryTable1)
        self.spinBox_14.setGeometry(QtCore.QRect(370, 700, 131, 31))
        self.spinBox_14.setStyleSheet("background-color:rgb(255, 255, 255);\n"
"border:2px solid;\n"
"border-radius:10;\n"
"")
        self.spinBox_14.setAlignment(QtCore.Qt.AlignCenter)
        self.spinBox_14.setObjectName("spinBox_14")
        self.label_2 = QtWidgets.QLabel(QueryTable1)
        self.label_2.setGeometry(QtCore.QRect(20, 60, 341, 31))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_2.setStyleSheet("background-color: rgb(250, 250, 125);\n"
"border:2px solid;\n"
"border-radius:10;\n"
"")
        self.label_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.spinBox1 = QtWidgets.QSpinBox(QueryTable1)
        self.spinBox1.setGeometry(QtCore.QRect(370, 100, 131, 31))
        self.spinBox1.setStyleSheet("background-color:rgb(255, 255, 255);\n"
"border:2px solid;\n"
"border-radius:10;\n"
"")
        self.spinBox1.setAlignment(QtCore.Qt.AlignCenter)
        self.spinBox1.setObjectName("spinBox1")
        self.textEdit_type_11 = QtWidgets.QTextEdit(QueryTable1)
        self.textEdit_type_11.setGeometry(QtCore.QRect(510, 580, 151, 31))
        self.textEdit_type_11.setStyleSheet("background-color:rgb(255, 255, 255);\n"
"border:2px solid;\n"
"border-radius:10;\n"
"")
        self.textEdit_type_11.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.textEdit_type_11.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textEdit_type_11.setObjectName("textEdit_type_11")
        self.label_1 = QtWidgets.QLabel(QueryTable1)
        self.label_1.setGeometry(QtCore.QRect(20, 20, 241, 31))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        self.label_1.setFont(font)
        self.label_1.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_1.setStyleSheet("background-color: rgb(250, 250, 125);\n"
"border:2px solid;\n"
"border-radius:10;\n"
"")
        self.label_1.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_1.setAlignment(QtCore.Qt.AlignCenter)
        self.label_1.setObjectName("label_1")
        self.textEdit_type_7 = QtWidgets.QTextEdit(QueryTable1)
        self.textEdit_type_7.setGeometry(QtCore.QRect(510, 380, 151, 31))
        self.textEdit_type_7.setStyleSheet("background-color:rgb(255, 255, 255);\n"
"border:2px solid;\n"
"border-radius:10;\n"
"")
        self.textEdit_type_7.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.textEdit_type_7.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textEdit_type_7.setObjectName("textEdit_type_7")
        self.textEditZapros2 = QtWidgets.QTextEdit(QueryTable1)
        self.textEditZapros2.setGeometry(QtCore.QRect(270, 300, 391, 31))
        self.textEditZapros2.setStyleSheet("background-color:rgb(255, 255, 255);\n"
"border:2px solid;\n"
"border-radius:10;\n"
"")
        self.textEditZapros2.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.textEditZapros2.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textEditZapros2.setObjectName("textEditZapros2")
        self.textEdit_source_3 = QtWidgets.QTextEdit(QueryTable1)
        self.textEdit_source_3.setGeometry(QtCore.QRect(20, 180, 341, 31))
        self.textEdit_source_3.setStyleSheet("background-color:rgb(255, 255, 255);\n"
"border:2px solid;\n"
"border-radius:10;\n"
"")
        self.textEdit_source_3.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textEdit_source_3.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textEdit_source_3.setObjectName("textEdit_source_3")
        self.spinBox_8 = QtWidgets.QSpinBox(QueryTable1)
        self.spinBox_8.setGeometry(QtCore.QRect(370, 420, 131, 31))
        self.spinBox_8.setStyleSheet("background-color:rgb(255, 255, 255);\n"
"border:2px solid;\n"
"border-radius:10;\n"
"")
        self.spinBox_8.setAlignment(QtCore.Qt.AlignCenter)
        self.spinBox_8.setObjectName("spinBox_8")
        self.textEdit_source_15 = QtWidgets.QTextEdit(QueryTable1)
        self.textEdit_source_15.setGeometry(QtCore.QRect(20, 740, 341, 31))
        self.textEdit_source_15.setStyleSheet("background-color:rgb(255, 255, 255);\n"
"border:2px solid;\n"
"border-radius:10;\n"
"")
        self.textEdit_source_15.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textEdit_source_15.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textEdit_source_15.setObjectName("textEdit_source_15")
        self.spinBox_24 = QtWidgets.QSpinBox(QueryTable1)
        self.spinBox_24.setGeometry(QtCore.QRect(1030, 420, 131, 31))
        self.spinBox_24.setStyleSheet("background-color:rgb(255, 255, 255);\n"
"border:2px solid;\n"
"border-radius:10;\n"
"")
        self.spinBox_24.setAlignment(QtCore.Qt.AlignCenter)
        self.spinBox_24.setObjectName("spinBox_24")
        self.spinBox_19 = QtWidgets.QSpinBox(QueryTable1)
        self.spinBox_19.setGeometry(QtCore.QRect(1030, 180, 131, 31))
        self.spinBox_19.setStyleSheet("background-color:rgb(255, 255, 255);\n"
"border:2px solid;\n"
"border-radius:10;\n"
"")
        self.spinBox_19.setAlignment(QtCore.Qt.AlignCenter)
        self.spinBox_19.setObjectName("spinBox_19")
        self.label_8 = QtWidgets.QLabel(QueryTable1)
        self.label_8.setGeometry(QtCore.QRect(680, 260, 241, 31))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_8.setStyleSheet("background-color: rgb(250, 250, 125);\n"
"border:2px solid;\n"
"border-radius:10;\n"
"")
        self.label_8.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.textEdit_source_23 = QtWidgets.QTextEdit(QueryTable1)
        self.textEdit_source_23.setGeometry(QtCore.QRect(680, 380, 341, 31))
        self.textEdit_source_23.setStyleSheet("background-color:rgb(255, 255, 255);\n"
"border:2px solid;\n"
"border-radius:10;\n"
"")
        self.textEdit_source_23.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textEdit_source_23.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textEdit_source_23.setObjectName("textEdit_source_23")
        self.textEdit_type_16 = QtWidgets.QTextEdit(QueryTable1)
        self.textEdit_type_16.setGeometry(QtCore.QRect(1170, 60, 151, 31))
        self.textEdit_type_16.setStyleSheet("background-color:rgb(255, 255, 255);\n"
"border:2px solid;\n"
"border-radius:10;\n"
"")
        self.textEdit_type_16.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.textEdit_type_16.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textEdit_type_16.setObjectName("textEdit_type_16")
        self.textEdit_type_21 = QtWidgets.QTextEdit(QueryTable1)
        self.textEdit_type_21.setGeometry(QtCore.QRect(1170, 300, 151, 31))
        self.textEdit_type_21.setStyleSheet("background-color:rgb(255, 255, 255);\n"
"border:2px solid;\n"
"border-radius:10;\n"
"")
        self.textEdit_type_21.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.textEdit_type_21.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textEdit_type_21.setObjectName("textEdit_type_21")
        self.textEdit_source_21 = QtWidgets.QTextEdit(QueryTable1)
        self.textEdit_source_21.setGeometry(QtCore.QRect(680, 300, 341, 31))
        self.textEdit_source_21.setStyleSheet("background-color:rgb(255, 255, 255);\n"
"border:2px solid;\n"
"border-radius:10;\n"
"")
        self.textEdit_source_21.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textEdit_source_21.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textEdit_source_21.setObjectName("textEdit_source_21")
        self.spinBox_17 = QtWidgets.QSpinBox(QueryTable1)
        self.spinBox_17.setGeometry(QtCore.QRect(1030, 100, 131, 31))
        self.spinBox_17.setStyleSheet("background-color:rgb(255, 255, 255);\n"
"border:2px solid;\n"
"border-radius:10;\n"
"")
        self.spinBox_17.setAlignment(QtCore.Qt.AlignCenter)
        self.spinBox_17.setObjectName("spinBox_17")
        self.textEdit_type_24 = QtWidgets.QTextEdit(QueryTable1)
        self.textEdit_type_24.setGeometry(QtCore.QRect(1170, 420, 151, 31))
        self.textEdit_type_24.setStyleSheet("background-color:rgb(255, 255, 255);\n"
"border:2px solid;\n"
"border-radius:10;\n"
"")
        self.textEdit_type_24.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.textEdit_type_24.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textEdit_type_24.setObjectName("textEdit_type_24")
        self.textEdit_type_19 = QtWidgets.QTextEdit(QueryTable1)
        self.textEdit_type_19.setGeometry(QtCore.QRect(1170, 180, 151, 31))
        self.textEdit_type_19.setStyleSheet("background-color:rgb(255, 255, 255);\n"
"border:2px solid;\n"
"border-radius:10;\n"
"")
        self.textEdit_type_19.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.textEdit_type_19.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textEdit_type_19.setObjectName("textEdit_type_19")
        self.textEdit_source_24 = QtWidgets.QTextEdit(QueryTable1)
        self.textEdit_source_24.setGeometry(QtCore.QRect(680, 420, 341, 31))
        self.textEdit_source_24.setStyleSheet("background-color:rgb(255, 255, 255);\n"
"border:2px solid;\n"
"border-radius:10;\n"
"")
        self.textEdit_source_24.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textEdit_source_24.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textEdit_source_24.setObjectName("textEdit_source_24")
        self.textEdit_type_23 = QtWidgets.QTextEdit(QueryTable1)
        self.textEdit_type_23.setGeometry(QtCore.QRect(1170, 380, 151, 31))
        self.textEdit_type_23.setStyleSheet("background-color:rgb(255, 255, 255);\n"
"border:2px solid;\n"
"border-radius:10;\n"
"")
        self.textEdit_type_23.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.textEdit_type_23.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textEdit_type_23.setObjectName("textEdit_type_23")
        self.spinBox_16 = QtWidgets.QSpinBox(QueryTable1)
        self.spinBox_16.setGeometry(QtCore.QRect(1030, 60, 131, 31))
        self.spinBox_16.setStyleSheet("background-color:rgb(255, 255, 255);\n"
"border:2px solid;\n"
"border-radius:10;\n"
"")
        self.spinBox_16.setAlignment(QtCore.Qt.AlignCenter)
        self.spinBox_16.setObjectName("spinBox_16")
        self.spinBox_21 = QtWidgets.QSpinBox(QueryTable1)
        self.spinBox_21.setGeometry(QtCore.QRect(1030, 300, 131, 31))
        self.spinBox_21.setStyleSheet("background-color:rgb(255, 255, 255);\n"
"border:2px solid;\n"
"border-radius:10;\n"
"")
        self.spinBox_21.setAlignment(QtCore.Qt.AlignCenter)
        self.spinBox_21.setObjectName("spinBox_21")
        self.textEdit_type_22 = QtWidgets.QTextEdit(QueryTable1)
        self.textEdit_type_22.setGeometry(QtCore.QRect(1170, 340, 151, 31))
        self.textEdit_type_22.setStyleSheet("background-color:rgb(255, 255, 255);\n"
"border:2px solid;\n"
"border-radius:10;\n"
"")
        self.textEdit_type_22.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.textEdit_type_22.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textEdit_type_22.setObjectName("textEdit_type_22")
        self.textEdit_source_22 = QtWidgets.QTextEdit(QueryTable1)
        self.textEdit_source_22.setGeometry(QtCore.QRect(680, 340, 341, 31))
        self.textEdit_source_22.setStyleSheet("background-color:rgb(255, 255, 255);\n"
"border:2px solid;\n"
"border-radius:10;\n"
"")
        self.textEdit_source_22.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textEdit_source_22.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textEdit_source_22.setObjectName("textEdit_source_22")
        self.textEditZapros4 = QtWidgets.QTextEdit(QueryTable1)
        self.textEditZapros4.setGeometry(QtCore.QRect(930, 20, 391, 31))
        self.textEditZapros4.setStyleSheet("background-color:rgb(255, 255, 255);\n"
"border:2px solid;\n"
"border-radius:10;\n"
"")
        self.textEditZapros4.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.textEditZapros4.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textEditZapros4.setObjectName("textEditZapros4")
        self.spinBox_23 = QtWidgets.QSpinBox(QueryTable1)
        self.spinBox_23.setGeometry(QtCore.QRect(1030, 380, 131, 31))
        self.spinBox_23.setStyleSheet("background-color:rgb(255, 255, 255);\n"
"border:2px solid;\n"
"border-radius:10;\n"
"")
        self.spinBox_23.setAlignment(QtCore.Qt.AlignCenter)
        self.spinBox_23.setObjectName("spinBox_23")
        self.textEdit_type_20 = QtWidgets.QTextEdit(QueryTable1)
        self.textEdit_type_20.setGeometry(QtCore.QRect(1170, 220, 151, 31))
        self.textEdit_type_20.setStyleSheet("background-color:rgb(255, 255, 255);\n"
"border:2px solid;\n"
"border-radius:10;\n"
"")
        self.textEdit_type_20.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.textEdit_type_20.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textEdit_type_20.setObjectName("textEdit_type_20")
        self.spinBox_25 = QtWidgets.QSpinBox(QueryTable1)
        self.spinBox_25.setGeometry(QtCore.QRect(1030, 460, 131, 31))
        self.spinBox_25.setStyleSheet("background-color:rgb(255, 255, 255);\n"
"border:2px solid;\n"
"border-radius:10;\n"
"")
        self.spinBox_25.setAlignment(QtCore.Qt.AlignCenter)
        self.spinBox_25.setObjectName("spinBox_25")
        self.textEdit_source_20 = QtWidgets.QTextEdit(QueryTable1)
        self.textEdit_source_20.setGeometry(QtCore.QRect(680, 220, 341, 31))
        self.textEdit_source_20.setStyleSheet("background-color:rgb(255, 255, 255);\n"
"border:2px solid;\n"
"border-radius:10;\n"
"")
        self.textEdit_source_20.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textEdit_source_20.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textEdit_source_20.setObjectName("textEdit_source_20")
        self.textEdit_source_17 = QtWidgets.QTextEdit(QueryTable1)
        self.textEdit_source_17.setGeometry(QtCore.QRect(680, 100, 341, 31))
        self.textEdit_source_17.setStyleSheet("background-color:rgb(255, 255, 255);\n"
"border:2px solid;\n"
"border-radius:10;\n"
"")
        self.textEdit_source_17.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textEdit_source_17.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textEdit_source_17.setObjectName("textEdit_source_17")
        self.textEdit_source_18 = QtWidgets.QTextEdit(QueryTable1)
        self.textEdit_source_18.setGeometry(QtCore.QRect(680, 140, 341, 31))
        self.textEdit_source_18.setStyleSheet("background-color:rgb(255, 255, 255);\n"
"border:2px solid;\n"
"border-radius:10;\n"
"")
        self.textEdit_source_18.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textEdit_source_18.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textEdit_source_18.setObjectName("textEdit_source_18")
        self.label_7 = QtWidgets.QLabel(QueryTable1)
        self.label_7.setGeometry(QtCore.QRect(680, 20, 241, 31))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_7.setStyleSheet("background-color: rgb(250, 250, 125);\n"
"border:2px solid;\n"
"border-radius:10;\n"
"")
        self.label_7.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.textEdit_source_25 = QtWidgets.QTextEdit(QueryTable1)
        self.textEdit_source_25.setGeometry(QtCore.QRect(680, 460, 341, 31))
        self.textEdit_source_25.setStyleSheet("background-color:rgb(255, 255, 255);\n"
"border:2px solid;\n"
"border-radius:10;\n"
"")
        self.textEdit_source_25.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textEdit_source_25.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textEdit_source_25.setObjectName("textEdit_source_25")
        self.textEdit_source_16 = QtWidgets.QTextEdit(QueryTable1)
        self.textEdit_source_16.setGeometry(QtCore.QRect(680, 60, 341, 31))
        self.textEdit_source_16.setStyleSheet("background-color:rgb(255, 255, 255);\n"
"border:2px solid;\n"
"border-radius:10;\n"
"")
        self.textEdit_source_16.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textEdit_source_16.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textEdit_source_16.setObjectName("textEdit_source_16")
        self.spinBox_18 = QtWidgets.QSpinBox(QueryTable1)
        self.spinBox_18.setGeometry(QtCore.QRect(1030, 140, 131, 31))
        self.spinBox_18.setStyleSheet("background-color:rgb(255, 255, 255);\n"
"border:2px solid;\n"
"border-radius:10;\n"
"")
        self.spinBox_18.setAlignment(QtCore.Qt.AlignCenter)
        self.spinBox_18.setObjectName("spinBox_18")
        self.spinBox_22 = QtWidgets.QSpinBox(QueryTable1)
        self.spinBox_22.setGeometry(QtCore.QRect(1030, 340, 131, 31))
        self.spinBox_22.setStyleSheet("background-color:rgb(255, 255, 255);\n"
"border:2px solid;\n"
"border-radius:10;\n"
"")
        self.spinBox_22.setAlignment(QtCore.Qt.AlignCenter)
        self.spinBox_22.setObjectName("spinBox_22")
        self.textEditZapros5 = QtWidgets.QTextEdit(QueryTable1)
        self.textEditZapros5.setGeometry(QtCore.QRect(930, 260, 391, 31))
        self.textEditZapros5.setStyleSheet("background-color:rgb(255, 255, 255);\n"
"border:2px solid;\n"
"border-radius:10;\n"
"")
        self.textEditZapros5.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.textEditZapros5.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textEditZapros5.setObjectName("textEditZapros5")
        self.textEdit_type_17 = QtWidgets.QTextEdit(QueryTable1)
        self.textEdit_type_17.setGeometry(QtCore.QRect(1170, 100, 151, 31))
        self.textEdit_type_17.setStyleSheet("background-color:rgb(255, 255, 255);\n"
"border:2px solid;\n"
"border-radius:10;\n"
"")
        self.textEdit_type_17.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.textEdit_type_17.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textEdit_type_17.setObjectName("textEdit_type_17")
        self.spinBox_20 = QtWidgets.QSpinBox(QueryTable1)
        self.spinBox_20.setGeometry(QtCore.QRect(1030, 220, 131, 31))
        self.spinBox_20.setStyleSheet("background-color:rgb(255, 255, 255);\n"
"border:2px solid;\n"
"border-radius:10;\n"
"")
        self.spinBox_20.setAlignment(QtCore.Qt.AlignCenter)
        self.spinBox_20.setObjectName("spinBox_20")
        self.textEdit_type_25 = QtWidgets.QTextEdit(QueryTable1)
        self.textEdit_type_25.setGeometry(QtCore.QRect(1170, 460, 151, 31))
        self.textEdit_type_25.setStyleSheet("background-color:rgb(255, 255, 255);\n"
"border:2px solid;\n"
"border-radius:10;\n"
"")
        self.textEdit_type_25.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.textEdit_type_25.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textEdit_type_25.setObjectName("textEdit_type_25")
        self.textEdit_type_18 = QtWidgets.QTextEdit(QueryTable1)
        self.textEdit_type_18.setGeometry(QtCore.QRect(1170, 140, 151, 31))
        self.textEdit_type_18.setStyleSheet("background-color:rgb(255, 255, 255);\n"
"border:2px solid;\n"
"border-radius:10;\n"
"")
        self.textEdit_type_18.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.textEdit_type_18.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textEdit_type_18.setObjectName("textEdit_type_18")
        self.textEdit_source_19 = QtWidgets.QTextEdit(QueryTable1)
        self.textEdit_source_19.setGeometry(QtCore.QRect(680, 180, 341, 31))
        self.textEdit_source_19.setStyleSheet("background-color:rgb(255, 255, 255);\n"
"border:2px solid;\n"
"border-radius:10;\n"
"")
        self.textEdit_source_19.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textEdit_source_19.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textEdit_source_19.setObjectName("textEdit_source_19")
        self.pushButton = QtWidgets.QPushButton(QueryTable1)
        self.pushButton.setGeometry(QtCore.QRect(1100, 740, 111, 28))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("background-color: rgb(250, 250, 125);\n"
"border-radius: 30px;\n"
"border: 1.5px solid")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_3 = QtWidgets.QPushButton(QueryTable1)
        self.pushButton_3.setGeometry(QtCore.QRect(990, 740, 93, 28))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setStyleSheet("background-color: rgb(250, 250, 125);\n"
"border-radius: 30px;\n"
"border: 1.5px solid")
        self.pushButton_3.setObjectName("pushButton_3")

        self.retranslateUi(QueryTable1)
        QtCore.QMetaObject.connectSlotsByName(QueryTable1)

    def retranslateUi(self, QueryTable1):
        _translate = QtCore.QCoreApplication.translate
        QueryTable1.setWindowTitle(_translate("QueryTable1", "Таблица запросов"))
        self.label_5.setText(_translate("QueryTable1", "Запрос:"))
        self.label_4.setText(_translate("QueryTable1", "Тип ресурса:"))
        self.label_6.setText(_translate("QueryTable1", "Запрос:"))
        self.label_3.setText(_translate("QueryTable1", "Оценка(1-10):"))
        self.label_2.setText(_translate("QueryTable1", "Источник:"))
        self.label_1.setText(_translate("QueryTable1", "Запрос:"))
        self.label_8.setText(_translate("QueryTable1", "Запрос:"))
        self.label_7.setText(_translate("QueryTable1", "Запрос:"))
        self.pushButton.setText(_translate("QueryTable1", "На главную "))
        self.pushButton_3.setText(_translate("QueryTable1", "Сохранить"))
